'use strict';
const labels = {vms:'VM一覧',volumes:'ストレージ',nics:'ネットワーク',placements:'配置ルール',actions:'例外処理',rules:'共通対応'};
const names = {id:'ID',name:'移行元VM名',os:'OS・バージョン',folder:'フォルダー',namespace:'移行先Namespace',target_name:'移行先VM名',mode:'移行方式',group:'切替グループ',dependencies:'先に移行するVMのID',vms:'関連VMのID',source:'移行元',kind:'種類',purpose:'用途',capacity_gib:'元容量 GiB',target_gib:'割当 GiB',strategy:'移行方法',storage_class:'StorageClass',endpoint:'接続先',access:'アクセス要件',consistency:'整合性確保手順',verified:'構成・対応確認済み',vm:'VMのID',source_vlan:'元VLAN',target_network:'移行先ネットワーク',target_vlan:'先VLAN',mac_policy:'MAC方針',ip_policy:'IP方針',source_rule:'元の配置ルール',target_rule:'移行先の配置方針',phase:'実行時点',definition:'実行定義の参照',success_condition:'成功条件',failure_policy:'失敗時',target:'対応先'};
const defaults = {
 vms:{id:'',name:'',os:'',folder:'',namespace:'',target_name:'',mode:'cold',group:'',dependencies:[]},
 volumes:{id:'',vms:[],source:'',kind:'virtual-disk',purpose:'',capacity_gib:0,target_gib:0,strategy:'copy',storage_class:'',endpoint:'',access:'single-writer',consistency:'',verified:false},
 nics:{id:'',vm:'',source:'',source_vlan:null,target_network:'',target_vlan:null,mac_policy:'preserve',ip_policy:'preserve',verified:false},
 placements:{id:'',vms:[],source_rule:'',target_rule:'',verified:false},
 actions:{id:'',vm:'',kind:'os-upgrade',phase:'before',definition:'',success_condition:'',failure_policy:'stop',verified:false},
 rules:{id:'',kind:'namespace',source:'',target:''}
};
const options = {'vms.mode':['warm','cold'],'volumes.kind':['virtual-disk','external','shared','special'],'volumes.strategy':['copy','reuse','reconnect','manual'],'volumes.access':['single-writer','multi-writer','read-only'],'nics.mac_policy':['preserve','regenerate'],'nics.ip_policy':['preserve','change'],'actions.kind':['os-upgrade','driver-change','script','manual'],'actions.phase':['before','before-cutover','after'],'actions.failure_policy':['stop','manual'],'rules.kind':['namespace','network','storage']};
const optionNames={warm:'Warm（事前転送）',cold:'Cold（停止後転送）','virtual-disk':'仮想ディスク',external:'外部接続',shared:'共有領域',special:'特殊デバイス',copy:'コピー',reuse:'継続利用',reconnect:'再接続',manual:'手動対応','single-writer':'単一書込み','multi-writer':'複数書込み','read-only':'読取り専用',preserve:'保持',regenerate:'再生成',change:'変更','os-upgrade':'OS更新','driver-change':'ドライバー変更',script:'独自処理',before:'移行前','before-cutover':'切替前',after:'移行後',stop:'停止',namespace:'Namespace',network:'ネットワーク',storage:'ストレージ'};
let data, revision, active='vms', dirty=false, selected=new Set(), pendingImport=null, observation=null, comparison=null;
const $ = id=>document.getElementById(id);
function element(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';}
async function request(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.error);return result;}
function updateRevision(){$('revision').textContent=`保存版 ${revision}${dirty?' • 未保存の変更あり':''}`;}
function changed(){dirty=true;updateRevision();$('results').replaceChildren(element('h2','編集内容が変わりました'),element('p','再度、事前チェックを実行してください。'));comparison=null;$('comparisonTable').replaceChildren();$('comparisonStatus').textContent='編集内容が変わりました。再度diffを表示してください。既存の実測は古い計画として判定されます。';}
function convert(field,value){const template=defaults[active][field];if(Array.isArray(template))return value.split(',').map(x=>x.trim()).filter(Boolean);if(typeof template==='boolean'){if(!['true','false'].includes(value))throw Error('確認済みは true / false で指定してください。');return value==='true';}if(typeof template==='number'||field.endsWith('_vlan')){if(field.endsWith('_vlan')&&value==='')return null;if(!/^\d+$/.test(value))throw Error('整数を入力してください。');return Number(value);}return value;}
function render(){
 $('tabs').replaceChildren();for(const [key,label] of Object.entries(labels)){const b=element('button',`${label} (${data[key].length})`);b.className=key===active?'active':'';b.onclick=()=>{active=key;selected.clear();render();};$('tabs').append(b);}
 const fields=Object.keys(defaults[active]);$('bulkField').replaceChildren(...fields.filter(f=>f!=='id').map(f=>{const o=element('option',names[f]);o.value=f;return o;}));
 $('hint').textContent='空欄の移行先には共通対応を適用します。ID配列はカンマ区切りです。VLANの空欄は未確認、0はタグなし。確認済みは入力内容の確認であり、実環境の適合を保証しません。';
 const table=$('editor');table.replaceChildren();const head=element('thead'),hr=element('tr');hr.append(element('th','選択'));for(const field of fields)hr.append(element('th',names[field]));head.append(hr);table.append(head);const body=element('tbody');
 const query=$('search').value.toLowerCase();data[active].forEach((row,index)=>{if(!JSON.stringify(row).toLowerCase().includes(query))return;const tr=element('tr'),td=element('td'),check=element('input');check.type='checkbox';check.checked=selected.has(index);check.setAttribute('aria-label',`${row.id}を選択`);check.onchange=()=>check.checked?selected.add(index):selected.delete(index);td.append(check);tr.append(td);
 for(const field of fields){const cell=element('td'), choices=options[`${active}.${field}`];const input=element(choices?'select':'input');input.setAttribute('aria-label',`${row.id} ${names[field]}`);if(choices){for(const value of choices){const o=element('option',optionNames[value]||value);o.value=value;input.append(o);}input.value=row[field];}else if(typeof row[field]==='boolean'){input.type='checkbox';input.checked=row[field];}else{input.type=(typeof defaults[active][field]==='number'||field.endsWith('_vlan'))?'number':'text';if(input.type==='number')input.min='0';input.value=Array.isArray(row[field])?row[field].join(','):row[field]??'';}
 input.onchange=()=>{try{row[field]=input.type==='checkbox'?input.checked:convert(field,input.value);changed();}catch(e){message(e.message,true);render();}};cell.append(input);tr.append(cell);}body.append(tr);});table.append(body);updateRevision();
}
function download(filename,object){const url=URL.createObjectURL(new Blob([JSON.stringify(object,null,2)],{type:'application/json'}));const a=element('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function action(id,fn){$(id).onclick=async()=>{const b=$(id);b.disabled=true;try{await fn();}catch(e){message(e.message,true);}finally{b.disabled=false;}};}
action('sample',async()=>{if(dirty&&!confirm('未保存の編集をサンプルで置き換えますか？'))return;data=await request('/api/sample');selected.clear();changed();render();message('サンプルを編集中です。確認後に保存してください。');});
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2_000_000)throw Error('入力は2MB以内です。');const imported=JSON.parse(await file.text());await request('/api/check',{inventory:imported});const diff=[];for(const table of Object.keys(labels)){const old=new Map(data[table].map(r=>[r.id,r])), next=new Map(imported[table].map(r=>[r.id,r]));for(const [id,row] of next){if(!old.has(id))diff.push(`${labels[table]}: 追加 ${id}`);else for(const field of Object.keys(row))if(JSON.stringify(old.get(id)[field])!==JSON.stringify(row[field]))diff.push(`${labels[table]} / ${id} / ${names[field]}: ${JSON.stringify(old.get(id)[field])} → ${JSON.stringify(row[field])}`);}for(const id of old.keys())if(!next.has(id))diff.push(`${labels[table]}: 削除 ${id}`);}pendingImport=imported;$('importDiff').textContent=diff.join('\n')||'変更はありません。';$('importPreview').hidden=false;message('取り込み差分を確認してください。現在の編集はまだ変更していません。');}catch(error){message(error.message,true);}finally{e.target.value='';}};
action('acceptImport',()=>{if(!pendingImport)return;data=pendingImport;pendingImport=null;$('importPreview').hidden=true;selected.clear();changed();render();message('取り込みました。確認後に保存してください。');});
action('cancelImport',()=>{pendingImport=null;$('importPreview').hidden=true;message('取り込みを取り消しました。');});
action('save',async()=>{const snapshot=JSON.stringify(data);const saved=await request('/api/inventory',{revision,inventory:JSON.parse(snapshot)});revision=saved.revision;dirty=JSON.stringify(data)!==snapshot;updateRevision();message(dirty?'新しい版として保存しました。保存中の編集は未保存です。':'新しい版として保存しました。');});
action('check',async()=>{const snapshot=JSON.stringify(data);const result=await request('/api/check',{inventory:JSON.parse(snapshot)});if(JSON.stringify(data)!==snapshot)throw Error('チェック中に編集されました。再度チェックしてください。');$('results').replaceChildren(element('h2',result.status));for(const issue of result.issues){const div=element('div');div.className='issue';div.append(element('strong',`${labels[issue.table]} / ${issue.id||'全体'}: ${issue.message}`),element('p',issue.remedy));$('results').append(div);}if(result.order.length)$('results').append(element('p',`移行順序: ${result.order.join(' → ')}`));$('results').append(element('p',`実環境で必要な確認: ${result.live_checks.join('、')}`));for(const p of result.provenance){$('results').append(element('p',`${p.id} / ${names[p.field]} → ${p.value||'未設定'} (${p.origin})`));}message(`ローカルチェック: ${result.issues.length}件の要対応。実際の移行はまだ実行できません。`);});
action('export',()=>download('inventory.json',data));
action('plan',async()=>{if(dirty)throw Error('変更を保存してから計画を書き出してください。');const plan=await request('/api/plan');if(plan.revision!==revision)throw Error('保存版が別の画面で変更されています。再読込みしてください。');download(`plan-revision-${plan.revision}.json`,plan);message('判定と対応元を含む計画を書き出しました。');});
action('add',()=>{const row=structuredClone(defaults[active]);row.id=crypto.randomUUID();data[active].push(row);changed();render();});
action('remove',()=>{data[active]=data[active].filter((_,i)=>!selected.has(i));selected.clear();changed();render();});
action('bulk',()=>{if(!selected.size)throw Error('行を選択してください。');const field=$('bulkField').value,value=convert(field,$('bulkValue').value),choices=options[`${active}.${field}`];if(choices&&!choices.includes(value))throw Error(`指定できる値: ${choices.join(', ')}`);for(const i of selected)data[active][i][field]=structuredClone(value);changed();render();});
$('search').oninput=render;
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
request('/api/inventory').then(saved=>{data=saved.inventory;revision=saved.revision;render();}).catch(e=>message(e.message,true));

const comparisonLabels={'planned-change':'計画した変更',unchanged:'計画上は維持',unresolved:'計画が未確定','stale-observation':'別の計画の実測','missing-resource':'移行先の対象が欠落',unobserved:'実測値が未取得',mismatch:'計画と不一致','expected-change':'計画した変更と一致',match:'計画と一致','unexpected-resource':'計画にない対象'};
const compareFields={name:'VM名',namespace:'配置先（元フォルダー → Namespace）',os:'OS',capacity_gib:'容量 GiB',destination:'領域の対応先',access:'アクセス要件',vms:'関連VM',network:'接続ネットワーク',vlan:'VLAN',vm:'接続VM',rule:'配置ルール',resource:'対象全体'};
function displayValue(value){if(value===null||value===undefined||value==='')return '未設定・未取得';return typeof value==='object'?JSON.stringify(value,null,2):String(value);}
function renderComparison(){const table=$('comparisonTable');table.replaceChildren();if(!comparison)return;const head=element('thead'),hr=element('tr');for(const title of ['対象','項目','移行元','計画した移行先','実測した移行先','判定'])hr.append(element('th',title));head.append(hr);table.append(head);const body=element('tbody');for(const row of comparison.rows){if($('differencesOnly').checked&&['match','unchanged'].includes(row.status))continue;const tr=element('tr');tr.dataset.status=row.status;for(const value of [`${labels[row.table]} / ${row.id}`,compareFields[row.field],displayValue(row.source),displayValue(row.expected),displayValue(row.observed),comparisonLabels[row.status]])tr.append(element('td',value));body.append(tr);}table.append(body);
 const summary=Object.entries(comparison.counts).map(([status,count])=>`${comparisonLabels[status]} ${count}件`).join(' / ');$('comparisonStatus').textContent=`${summary||'対象なし'}。${comparison.captured_at?`実測日時: ${comparison.captured_at}。`:''}${comparison.observation_stale?'実測の計画識別子が異なります。現在の計画で再取得してください。':comparison.observed_fields_match?'比較対象の実測項目は一致しています。':'未確定・未取得・不一致の項目を確認してください。'} この比較だけで移行完了とは判定しません。`;
}
async function refreshComparison(candidate=observation){const snapshot=JSON.stringify(data);const report=await request('/api/compare',{inventory:JSON.parse(snapshot),observation:candidate});if(JSON.stringify(data)!==snapshot)throw Error('比較中に編集されました。再度diffを表示してください。');observation=candidate;comparison=report;renderComparison();}
action('compare',()=>refreshComparison());
action('observationTemplate',async()=>{const template=await request('/api/observation-template',{inventory:data});download('target-observation.json',template);message('実測値はすべてnullです。移行先で確認した値と取得日時を入力してください。計画値を実測値として転記しないでください。');});
$('observationImport').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2_000_000)throw Error('実測JSONは2MB以内です。');await refreshComparison(JSON.parse(await file.text()));message('移行先の実測を比較しました。');}catch(error){message(error.message,true);}finally{e.target.value='';}};
action('clearObservation',()=>refreshComparison(null));
action('exportComparison',()=>{if(!comparison)throw Error('先にdiffを表示してください。');download('migration-diff.json',comparison);});
$('differencesOnly').onchange=renderComparison;

